### ISSUE TITLE
Setup lazy loader for particles video

### ISSUE THREAD

**Issue by kadenzipfel** [nerdwise/nerdwise-website#112]

**Comment by kadenzipfel** [comment]
Was planning on using loadImage from toolbox, but looks like I'll have to make a new function for this.

**Comment by angusm** [comment]
Please model the new code off of loadImage and once it's ready and working in Nerdwise port it over to Toolbox :)

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/nerdwise-website/pull/136
