### ISSUE TITLE
`grow build` removes classes from yaml forms

### ISSUE THREAD

**Issue by kadenzipfel** [nerdwise/nerdwise-website#138]

**Comment by kadenzipfel** [comment]
Solved by tossing the classes right into the html since it's not dynamically written anyway.

**Comment by angusm** [comment]
Just noting here, the solve I use is to have css_classes since classes is a special value for grow YAML files, and in general Class is not specific enough in a programming context since it could also refer to Class the programming term used in Typescript/Javascript.
