### ISSUE TITLE
Contact us section

### ISSUE THREAD

**Issue by angusm** [nerdwise/nerdwise-website#29]
We'll need a robust contact us section, as well as a contact-us form.

I'll leave implementation details up to you on how best to handle the form. If there's free or off the shelf solutions we can tap into with an API or something (ideally we don't want to run a dynamic server), then let's go with that. Might take some research.

**Comment by kadenzipfel** [comment]
Here's a design idea for the contact page.

![contact-page](https://user-images.githubusercontent.com/30579067/56605928-04c73f80-65ba-11e9-83eb-6a6aca796d95.png)

The idea is that the right side begins empty, and upon clicking one of the blue links, the corresponding contact inputs slide and fade in from left to right.

For this I have an example of what it would like if "Let's just chat" was selected.

Also, if you click on the email, it will do a mailto:

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/nerdwise-website/pull/111
